map_type: costmap

obstacle_range: 4.0     # The maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
raytrace_range: 7.5     # The range in meters at which to raytrace out obstacles from the map using sensor data.

#transform_tolerance: 0.2
#inflation_radius: 0.2

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_bot/laser/scan, marking: true, clearing: true}