local_costmap:
   global_frame: odom                   # The local frame for the costmap to operate in. 
   robot_base_frame: robot_footprint    # The name of the frame for the base link of the robot.
   update_frequency: 10.0               # The frequency (Hz) at which the map is updated.
   publish_frequency: 10.0              # The frequency (Hz) at which the map publishes display information.
   width: 5.0                           # The width of the map in meters.
   height: 5.0                          # The height of the map in meters.
   resolution: 0.02                     # The resolution of the map in meters/cell using Hokuyo URG-04LX-UG01 laser scanner with resolution of 0.01mm
   static_map: false
   rolling_window: true                 # Whether or not to use a rolling window version of the costmap. 
                                        # If the static_map parameter is set to true, this parameter must be set to false.