TrajectoryPlannerROS:

  holonomic_robot: false        # For non-holonomic robots, no strafing velocity commands will be issued to the base.
  meter_scoring: true           # scoring in meters rather than cells
  #publish_cost_grid_pc: false   # Whether or not to publish the cost grid that the planner will use when planning. 
  #latch_xy_goal_tolerance: false # If goal tolerance is latched, when the robot reaches the goal xy location it will simply rotate in place, even if it ends up outside the goal tolerance while it is doing so. 
  #yaw_goal_tolerance: 0.05      # The tolerance in radians for the controller in yaw/rotation when achieving its goal 
  #xy_goal_tolerance : 0.05      # The tolerance in meters for the controller in the x & y distance when achieving a goal
  sim_time: 1.0                 
  controller_frequency: 10.0    
  #acc_lim_x: 2.5
  #acc_lim_y: 2.5
  #acc_lim_theta: 3.0
  #max_vel_x: 0.5
  #min_vel_x: 0.1
  #max_vel_theta: 1.0
  #min_vel_theta: -1.0
  #min_in_place_vel_theta: 0.4
  pdist_scale: 0.6              
  gdist_scale: 0.8              